'use client';

import './globals.css';
import { Inter } from 'next/font/google';
import { ChainId, ThirdwebProvider } from '@thirdweb-dev/react';
import { StateContextProvider } from '@/Context/ReligiousContext';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//    title: 'Create Next App',
//    description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
   return (
      <ThirdwebProvider activeChain={ChainId.Mumbai}>
         <StateContextProvider>
            <html lang="en">
               <body>{children}</body>
            </html>
         </StateContextProvider>
      </ThirdwebProvider>
   );
}
